### ISSUE TITLE
Unable to retrieve queue and history items from MediathekArr Downloader

### ISSUE THREAD

**Issue by Subito** [PCJones/MediathekArr#3]
Hi! 

freshly installed MediathekArr gives me the following error:

```
Unable to retrieve queue and history items from Mediathekarr Downloader: Could not convert string to decimal: Unknown. Path 'slots[2].mb', line 32, position 21. (Json snippet '     "mb": "Unknown"<--error-->,')
```

It seems that files get downloaded, but nothing is reported back to sonarr?

**Comment by Subito** [comment]
The download client is shown as "unavailable due to errors" afterwards.

**Comment by Subito** [comment]
This was an error on my part. I misread the docker-compose and entered the wrong values for my environment. After fixing this, this works.

**Comment by memehammad** [comment]
Can you go into detail on what the issue was?

**Comment by Subito** [comment]
I put the wrong values in my `DOWNLOAD_FOLDER_PATH_MAPPING` which made strange errors. Fixing my volume mount and `DOWNLOAD_FOLDER_PATH_MAPPING` fixed most of these problems.

**Comment by PCJones** [comment]
> Can you go into detail on what the issue was?

Do you have this issue? If yes, please share your docker compose / unraid settings
