### ISSUE TITLE
ZDF Magazin-Royale: Unknown episode or series.

### ISSUE THREAD

**Issue by fuchsi3010** [PCJones/MediathekArr#9]
hi,
first of all: thank you very much for this, i have been looking for something like this for 2 or 3 years, now i can finally retire my shitty scripts :-)

i set up mediathekarr today and wanted to try to download an episode of ''zdf magazin royale".
i noticed it doesn't recognize the episode as part of this series.
i think this will prevent it from automatically downloading? i'll see what happens tonight, and report back.

for me this isn't a big issue, i'll just manually download. 
wanted to report this, just to have it documented :-)

picture: 

![image](https://github.com/user-attachments/assets/14166cea-f8ac-499a-adef-22c646624b1a)

hovering over the "!" gives me: "Unable to identify correct episode(s) using release name and scene mappings"

**Comment by fuchsi3010** [comment]
another thing: the grabbed media is not automatically imported, because the season mediathekarr provides (2024) does not match the one sonarr gets from TheTVDB (Season 9).

I think this did match some time back, seems some spaßvogel restructured the seasons on tvdb? all of my old episodes aren't recognized either...

![image](https://github.com/user-attachments/assets/e92aff5b-6953-46b7-99fe-5c32b310ea08)

**Comment by PCJones** [comment]
Hi, glad you enjoy it!

First of all, if you have Discord I'll highly recommend that you join our Server for further discussions (only if you want to of course): https://discord.gg/pZrrMcJMQM

Now back to topic; the issue with this is that ARD/ZDF Mediathek metadata is pure chaos. I'm actively working on a huge update that will fix all these problems by allowing me to define specific filtering and matching rules on a per show basis. 

If you want to test this already, all you need to do is set this as MediathekArr indexer url:
`https://nzb.mediathekarr.pcjones.de`

ZDF Magazin Royale and other shows that didn't work properly before should work fine now for 99% of episodes (Tatort for example only works for ~30% of all episodes with the version you are using). For some shows (like ZDF Magazin Royale) you need to set the show type to daily for it to work.

**Comment by fuchsi3010** [comment]
hi,

i set this in the prowlarr entry, and now it works!

![image](https://github.com/user-attachments/assets/2f06b511-9d40-41ab-9223-37a1fb65fc5c)

i'm guessing i should change this back to my local mediathekarr instance, once the new version is released?

thanks!

**Comment by PCJones** [comment]
> hi,
> 
> i set this in the prowlarr entry, and now it works!
> 
> ![image](https://private-user-images.githubusercontent.com/37498115/393499070-2f06b511-9d40-41ab-9223-37a1fb65fc5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODQ0NTQsIm5iZiI6MTczMzU4NDE1NCwicGF0aCI6Ii8zNzQ5ODExNS8zOTM0OTkwNzAtMmYwNmI1MTEtOWQ0MC00MWFiLTkyMjMtMzdhMWZiNjVmYzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE1MDkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NjVkODkwNWFjOGZiNjE3NjQyZGZiNDdiOWNhNmUxYTYzODA4ODIzOWEyMzJlNmVlZTY2MWYzMzAzYTA3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mU1e8MhEnP4BChhjOGM1EtGyza7G_r_O3d_j-w68bC4)
> 
> i'm guessing i should change this back to my local mediathekarr instance, once the new version is released?
> 
> thanks!

Exactly! Once the 1.0 update releases you should use your local API again :)
